<main>
    <h1>Connexion</h1>
    <form action="index.php?route=check-connexion" method="POST">
        <fieldset>
            <label for="email">Email :</label>
            <input type="email" id="email" name="email">
        </fieldset>
        <fieldset>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password">
        </fieldset>
        <button type="submit">Se connecter</button>
    </form>
</main>
