<main>
    <h1>Inscription</h1>
    <form action="index.php?route=check-register" method="POST">
        <fieldset>
            <label for="firstName">Prénom :</label>
            <input type="text" id="firstName" name="firstName">
        </fieldset>
        <fieldset>
            <label for="lastName">Nom :</label>
            <input type="text" id="lastName" name="lastName">
        </fieldset>
        <fieldset>
            <label for="email">Email :</label>
            <input type="email" id="email" name="email">
        </fieldset>
        <fieldset>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password">
        </fieldset>
        
        <button type="submit">S'inscrire</button>
    </form>
</main>